### ISSUE TITLE
[BUG] Text Not Properly Word-Wrapped in System Information Display

### ISSUE THREAD

**Issue by kodebarista** [cosmic-utils/examine#22]
**Issue:**
On the system information screen, text in the right-side pane is not properly word-wrapped, causing it to display as a vertical line rather than wrapping to fit the container width. This layout issue makes the information difficult to read.

This issue is reproducible in each page with some param info

**Propose solution:**
- Implement word-wrap for entities on left so that when windows size is shrinked it makes space for information on right.
- Prevent shrinking window after certain point. Currently windows can be shrinked to a straight line

![image](https://github.com/user-attachments/assets/1711a12a-9056-4af9-9a47-c9701684fe7f)

App Window when shrinked (It can further be shrinked)
![image](https://github.com/user-attachments/assets/bab3269a-61dc-42b7-a76e-ca09af4202a3)

**Comment by sungsphinx** [comment]
Sorry, looks like I missed this issue. I am working on updating to the latest libcosmic version, so I will make sure there is a minimum window size set before I push to a branch.

**Comment by sungsphinx** [comment]
@CodingHashira could you see if #23 helps?
